name: "SAM Delete"

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR  

jobs:
  delete:
    name: "delete"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/sam-cicd-delete.yaml@main
    secrets: 
      aws-region:  ${{ secrets.AWS_REGION }}
      devl-aws-cloudformation-role-arn: ${{ secrets.DEVL_AWS_CLOUDFORMATION_ROLE_ARN }}
      devl-aws-sam-pipeline-role-arn: ${{ secrets.DEVL_AWS_SAM_PIPELINE_ROLE_ARN }}
      devl-kms-key-arn:  ${{ secrets.DEVL_AWS_KMS_KEY_ARN }}
      test-aws-cloudformation-role-arn: ${{ secrets.TEST_AWS_CLOUDFORMATION_ROLE_ARN }}
      test-aws-sam-pipeline-role-arn: ${{ secrets.TEST_AWS_SAM_PIPELINE_ROLE_ARN }}
      test-kms-key-arn:  ${{ secrets.TEST_AWS_KMS_KEY_ARN }}
      prod-aws-cloudformation-role-arn: ${{ secrets.PROD_AWS_CLOUDFORMATION_ROLE_ARN }}
      prod-aws-sam-pipeline-role-arn: ${{ secrets.PROD_AWS_SAM_PIPELINE_ROLE_ARN }}
      prod-kms-key-arn:  ${{ secrets.PROD_AWS_KMS_KEY_ARN }}