name: "SAM Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature**'
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**.yaml'

permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  issues: write
  pull-requests: write # This is required for gh bot to comment PR  

jobs:
  create:
    name: "sam"
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/sam-cicd-create.yaml@main
    with:
      deploy-reviewer-test: 142895397
      deploy-reviewer-prod: 144537759
      pr-approver: bsubhamay-approver
    secrets: 
      git-token: ${{ secrets.GIT_TOKEN }}
      aws-region:  ${{ secrets.AWS_REGION }}
      devl-aws-cloudformation-role-arn: ${{ secrets.DEVL_AWS_CLOUDFORMATION_ROLE_ARN }}
      devl-aws-sam-pipeline-role-arn: ${{ secrets.DEVL_AWS_SAM_PIPELINE_ROLE_ARN }}
      devl-kms-key-arn:  ${{ secrets.DEVL_AWS_KMS_KEY_ARN }}
      devl-aws-sam-artifacts-bucket-name: ${{ secrets.DEVL_AWS_SAM_ARTIFACTS_BUCKET_NAME }}
      test-aws-cloudformation-role-arn: ${{ secrets.TEST_AWS_CLOUDFORMATION_ROLE_ARN }}
      test-aws-sam-pipeline-role-arn: ${{ secrets.TEST_AWS_SAM_PIPELINE_ROLE_ARN }}
      test-kms-key-arn: ${{ secrets.TEST_AWS_KMS_KEY_ARN }}
      test-aws-sam-artifacts-bucket-name: ${{ secrets.TEST_AWS_SAM_ARTIFACTS_BUCKET_NAME }}
      prod-aws-cloudformation-role-arn: ${{ secrets.PROD_AWS_CLOUDFORMATION_ROLE_ARN }}
      prod-aws-sam-pipeline-role-arn: ${{ secrets.PROD_AWS_SAM_PIPELINE_ROLE_ARN }}
      prod-kms-key-arn: ${{ secrets.PROD_AWS_KMS_KEY_ARN }}
      prod-aws-sam-artifacts-bucket-name: ${{ secrets.PROD_AWS_SAM_ARTIFACTS_BUCKET_NAME }}